//
//  Postcard.swift
//  stamppal
//
//  Created by Muhammad Alief Rahman Fardillah on 03/09/26.
//

import Foundation
import SwiftData

@Model
final class Postcard {

    var id: UUID

    // Used by existing/sample postcards
    var imageName: String?

    // Used by photos taken from the camera
    var imageData: Data?

    var sender: String
    var date: String
    var message: String

    // Stamp generated by AI
    var stampData: Data?

    init(
        id: UUID = UUID(),
        imageName: String? = nil,
        imageData: Data? = nil,
        sender: String,
        date: String,
        message: String,
        stampData: Data? = nil
    ) {
        self.id = id
        self.imageName = imageName
        self.imageData = imageData
        self.sender = sender
        self.date = date
        self.message = message
        self.stampData = stampData
    }
}
